env:
  global:
    secure: UKVtopwo4zgYfyQFY/cN3CeYzoiOkqggt3vbJnJP0eyh5Wr8n64/yfurywyOr6Vxa7si3cLGSoakMRfO1YI+uptJ945Y8DUaSNkXqDXIXPK7Vt+q310/88earSasGbEAebLIGVsra7VMkinLDLbIdLsJe1BU0AN5uJ6jNBTZ4rybQoshWYT3iGtc46/XEhSBiinTKwhdH+dc6aawUtJj5WGGBcJy1jPgRWC0jjTpqzLkzvi4kYWqVjpYG3AF1DYJqDmovmdxjuz+UGUwLWEkSgDwnXLphcY9feIdZLpk04mFsmtZFM8jc2XjwMs7Sd2vI/6t6en6VpYmN+WvH9LT4xLT5+LHgJvQ+S71ZrTWLg05XBMGskwKx0pJcGmAJUgPyIVHdrlzb7rkMXA+j2FiiqrnpCVw0dTpWmgzwcFE7RJ6arY57swVQCdGEU2hbnjQgOem72m4hFiTmj71HDuqQSjbQOh16mffjsDcQvfp2dUuRxWqRhx2SB/Zmo/X7eBzVP5Y2vvNNs4FzfL5GADZPSBVYtxQX1CSY3WvzW5VQSb0KQRL03h0XPJ/cDZ6COsdW17VcuzfJxjOAXe1sk1PXS9ZInTa2nXSyTjPvQkNbcfjF4FRZsgSRPq2pf5QpCJWbNk2USXM4jM9zaF87KkWtzbxxCEkdLVZY1KHbFOPxg4=

services:
  - docker

script:
  - make
  - make test

after_success:
  - if [[ "$TRAVIS_PULL_REQUEST" == "false" && "$TRAVIS_BRANCH" == "master" ]]; then
    docker login -u="existenz" -p="$DOCKER_PASSWORD"; docker push existenz/travis-cli:latest;
    fi

